name:                rpi-speaker-zones
version:             0.1.0.0
github:              "githubuser/rpi-speaker-zones"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rpi-speaker-zones#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  rpi-speaker-zones:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rpi-speaker-zones
    - directory
    - file-embed
    - http-types
    - microlens
    - scotty
    - text
    - transformers

tests:
  rpi-speaker-zones-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rpi-speaker-zones
